#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
picom &
# polybar &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# killall -q polybar
# while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# polybar -q other -c "$HOME/.config/polybar/config.ini" &
# polybar -q coolworkspaces -c "$HOME/.config/polybar/config.ini" &

### Other stuff
# bspc rule -a qemu-system-i386 state=floating
bspc config external_rules_command ~/.config/bspwm/ext.sh

# In order for resizing with alt and mouse to work
bspc config pointer_modifier mod1
bspc config pointer_action1 move
